name: Horusec Static Analysis

on:
  push:
    branches:
      - main

jobs:
  horusec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install Horusec CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec-cli/main/deployments/scripts/install.sh | bash

    - name: Run Horusec
      run: horusec start -p="." -a

