name: Horusec SAST

on:
  push:
    branches:
      - main

jobs:
  horusec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Horusec CLI
        run: go install github.com/ZupIT/horusec-cli/cmd/horusec

      - name: Run Horusec SAST
        run: horusec start -p . -r json -o horusec-report.json
        
      - name: Upload Horusec Report
        uses: actions/upload-artifact@v2
        with:
          name: Horusec Report
          path: horusec-report.json
